mk-car-repository
JacobTheLiar/sda-4team-carrent pull request #13
Opened 2019-10-27 13:57 UTC by maciejkryger

added repositories: Car, CarModel, CarReview

2019-10-27 14:10 UTC, CKochanski requested changes
Testy!!!!

2019-10-27 14:10 UTC, CKochanski commented on src/main/java/pl/team/carrent/repository/CarRepository.java
> +    Car findByPlateNr(String plateNr);
Zwróć `Optional<Car>`

2019-10-27 14:10 UTC, CKochanski commented on src/main/java/pl/team/carrent/repository/CarRepository.java
> +    Car findByVin(String vin);
Tu też

2019-10-27 14:10 UTC, CKochanski commented on src/main/java/pl/team/carrent/repository/CarReviewRepository.java
> +    Car findByCar_PlateNr(String plateNr);
Tu też

2019-10-27 14:10 UTC, CKochanski commented on src/main/java/pl/team/carrent/repository/CarReviewRepository.java
> +    Car findByCar_VinAnd(String vin);
Też

2019-10-27 14:10 UTC, CKochanski commented on src/main/java/pl/team/carrent/repository/CarReviewRepository.java
> +public interface CarReviewRepository extends JpaRepository<CarReview, String> {
Typ identyfikatora jest `Integer`

2019-10-27 14:10 UTC, CKochanski commented on src/main/java/pl/team/carrent/repository/CarRepository.java
> +public interface CarRepository extends JpaRepository<Car, String> {
Tutaj `Integer` jako id

2019-10-27 19:40 UTC, JacobTheLiar commented on src/main/java/pl/team/carrent/repository/CarReviewRepository.java
> +    Car findByCar_VinAnd(String vin);
a czy nie powinno być findByCarVin

2019-10-27 19:41 UTC, JacobTheLiar commented on src/main/java/pl/team/carrent/repository/CarReviewRepository.java
> +    Car findByCar_PlateNr(String plateNr);
czy nie powinno być findByCarPlateNr

2019-10-28 06:57 UTC, maciejkryger commented on src/main/java/pl/team/carrent/repository/CarReviewRepository.java
> +    Car findByCar_PlateNr(String plateNr);
tak podpowiedział IntelliJ Ultimate

2019-10-28 06:57 UTC, maciejkryger commented on src/main/java/pl/team/carrent/repository/CarReviewRepository.java
> +    Car findByCar_VinAnd(String vin);
tak podpowiedział IntelliJ Ultimate

2019-10-28 08:37 UTC, JacobTheLiar commented on src/main/java/pl/team/carrent/repository/CarReviewRepository.java
> +    Car findByCar_VinAnd(String vin);
a testy zrobiłeś?

2019-10-28 08:37 UTC, JacobTheLiar commented on src/main/java/pl/team/carrent/repository/CarReviewRepository.java
> +    Car findByCar_PlateNr(String plateNr);
a testy zrobiłeś?

2019-10-28 17:31 UTC, maciejkryger commented on src/main/java/pl/team/carrent/repository/CarReviewRepository.java
> +    Car findByCar_VinAnd(String vin);
jeszcze nie, z testami nie mogę sobie jeszcze poradzić

2019-10-28 17:44 UTC, maciejkryger commented
Jakub, zerknij czy mogę potwiedzić merge

2019-10-28 18:16 UTC, JacobTheLiar commented
dorzucisz więcej testów? czy może wolałbyś skupić się na dalszej pracy?

2019-10-28 18:18 UTC, JacobTheLiar approved these changes

2019-10-29 18:55 UTC, merged