Rent Repository with tests
JacobTheLiar/sda-4team-carrent pull request #25
Opened 2019-11-05 18:56 UTC by maciejkryger

RentRepository z testami
testy puszczane osobno przechodza, a razem kumuluja aktual i nie przechodzą - nie mogę wyciągnąć tworzonych instancji nad klasy testowe, bo nie działają metody na repositoriach

brakuje repo do employee i promotion by zrobić wszystkie testy dla rent

2019-11-05 19:05 UTC, JacobTheLiar commented
no to poczekamy na kolegów, sobota już niedaleko. damy radę sporo zrobić w weekend.

2019-11-09 08:29 UTC, CKochanski requested changes

2019-11-09 08:29 UTC, CKochanski commented on src/test/java/pl/team/carrent/repository/RentRepositoryTest.java
> +public class RentRepositoryTest {
Dodaj adnotacje `@Transactional` - zostają Ci w bazie stare rekordy z poprzednich testów

2019-11-09 08:29 UTC, CKochanski commented on src/test/java/pl/team/carrent/repository/RentRepositoryTest.java
> +    RentRepository rentRepository;
Wszystkie pola `private`

2019-11-09 09:02 UTC, CKochanski approved these changes

2019-11-09 09:03 UTC, merged