mk-carmodel-controller
JacobTheLiar/sda-4team-carrent pull request #41
Opened 2019-11-13 22:22 UTC by maciejkryger

…, needed to edit item in base, 3 views - CarModels, edit end add new CarModel, all works !

2019-11-14 08:11 UTC, JacobTheLiar requested changes
oto moje uwagi

2019-11-14 08:11 UTC, JacobTheLiar commented on src/main/webapp/WEB-INF/views/carModelAddUpdate.jsp
> +        <c:if test="${update==true}">
wystarczy samo `"${update}"`

2019-11-14 08:11 UTC, JacobTheLiar commented on src/main/webapp/WEB-INF/views/carModelAddUpdate.jsp
> +        <c:if test="${update==false}">
można zastąpić `${!update}`

2019-11-14 08:11 UTC, JacobTheLiar commented on src/main/webapp/WEB-INF/views/carModel.jsp
> +        </form>
czy `<form>..</form>` nie powinien być wewnątrz pętelki?

2019-11-14 08:11 UTC, JacobTheLiar commented on src/main/webapp/WEB-INF/views/carModel.jsp
> +            </select>
może spróbuj przeiterować po enumie. Należałoby zmodyfikować troszkę enuma ale będzie później bardziej uniwersalne. przykład enuma

```
public enum MyEnum{
    ONE("opcja jeden"),  TWO("opcja dwa");

    private String description;
    MyEnum(String description) {this.description = description;}

    @Override
    public String toString() {return description;}
}
```

2019-11-14 08:11 UTC, JacobTheLiar commented on src/main/java/pl/team/carrent/car_model/CarModelService.java
> +    }
zrób wyjątek w przypadku kiedy nie zostanie znaleziony model samochodu o podanym id. 
zobacz w fakturach jak to wygląda.
```
    public Invoice getInvoiceById(int invoiceId){
        return invoiceRepository.findById(invoiceId)
                .orElseThrow(() -> new InvoiceNotExistException("invoiceId: " + invoiceId));
    }
```
i do tego klasa z wyjątkiem
```
public class InvoiceNotExistException extends RuntimeException{
    public InvoiceNotExistException(String message){
        super(message);
    }
}
```

2019-11-14 08:11 UTC, JacobTheLiar commented on src/main/java/pl/team/carrent/car_model/CarModelController.java
> +    }
czy nie zadziała tak samo jak przy edycji `postCarModelSaveModel`?

2019-11-14 08:11 UTC, JacobTheLiar commented on src/main/java/pl/team/carrent/car_model/CarModelController.java
> +    ModelAndView modelAndViewToAddAndEdit = new ModelAndView("carModelAddUpdate");
private i może nad konstruktor.

2019-11-14 18:56 UTC, maciejkryger commented on src/main/webapp/WEB-INF/views/carModel.jsp
> +            </select>
Nie za bardzo wiem czemu to ma służyć , mógłbyś cis więcej o tym napisać?

2019-11-15 10:15 UTC, JacobTheLiar commented on src/main/webapp/WEB-INF/views/carModel.jsp
> +            </select>
Ogólnie ogranicza się umieszczanie danych, które mogą ulec zmianie na sztywno w kodzie. Wyobraź sobie, iż dodajesz kolejna opcję szukania, wtedy musisz dodać enuma któego obsługujesz w kodzie java gdzie to obsługujesz i musisz poprawić dodatkowo w jsp (w jednym lub więcej przypadków) tą wartość.

Dodatkowo jest problem kiedy poprawisz którąś wartość enuma musisz pamiętać by poprawić znowu w jsp.

Wyobraź sobie że masz więcej tych widoków (jsp), narasta zbędna praca i miejsce gdzie może powstać błąd.

A tak samo się wypełni dostępnymi opcjami. i do tego mniejszy plik jsp. 
Również wydaje mi się to bardziej eleganckie.

2019-11-16 08:08 UTC, CKochanski requested changes

2019-11-16 08:08 UTC, CKochanski commented on src/main/java/pl/team/carrent/car_model/CarModelController.java
> +    @PostMapping(value = "/")
`GetMapping` - czyli merge tej metody z tą u góry

2019-11-16 08:08 UTC, CKochanski commented on src/main/java/pl/team/carrent/car_model/CarModelController.java
> +    ModelAndView modelAndView = new ModelAndView("carModel");
Nie twórzmy współdzielonych widoków, skoro są modyfikowalne

2019-11-16 08:08 UTC, CKochanski commented on src/main/java/pl/team/carrent/car_model/CarModelController.java
> +        return modelAndView;
`Redirect na widok?`

2019-11-16 08:08 UTC, CKochanski commented on src/main/java/pl/team/carrent/car_model/CarModelController.java
> +    public ModelAndView postCarModelAddNewModel(@RequestParam String mark, @RequestParam String model,
Może zrobimy tutaj jakiś obiekt typu `SearchParameters` i przekażemy go w body tego posta? 6 parametrów metody wygląda średnio, wg sztuki powinny być max 3 :)

2019-11-16 08:08 UTC, CKochanski commented on src/main/java/pl/team/carrent/car_model/CarModelController.java
> +    public ModelAndView postCarModelEditModel(@RequestParam int id) {
`PathVariable` zamiast `RequestParam`

2019-11-16 08:16 UTC, maciejkryger commented on src/main/webapp/WEB-INF/views/carModelAddUpdate.jsp
> +        <c:if test="${update==false}">
poprawiłem

2019-11-16 08:16 UTC, maciejkryger commented on src/main/webapp/WEB-INF/views/carModelAddUpdate.jsp
> +        <c:if test="${update==true}">
poprawiłem

2019-11-16 08:22 UTC, maciejkryger commented on src/main/webapp/WEB-INF/views/carModel.jsp
> +        </form>
poprawione, faktycznie działało jedynie na pierwszym rekordzie

2019-11-16 08:32 UTC, maciejkryger commented on src/main/java/pl/team/carrent/car_model/CarModelController.java
> +    @PostMapping(value = "/")
jak może get obsłużyć post za jednym razem? nie rozumiem idei

2019-11-16 08:58 UTC, maciejkryger commented on src/main/java/pl/team/carrent/car_model/CarModelController.java
> +    ModelAndView modelAndViewToAddAndEdit = new ModelAndView("carModelAddUpdate");
wywaliłem to i zrobiłem redirecta

2019-11-16 08:58 UTC, maciejkryger commented on src/main/java/pl/team/carrent/car_model/CarModelController.java
> +        return modelAndView;
zrobione, dzięki

2019-11-16 08:59 UTC, maciejkryger commented on src/main/java/pl/team/carrent/car_model/CarModelController.java
> +    public ModelAndView postCarModelAddNewModel(@RequestParam String mark, @RequestParam String model,
zrobiłem Model Atribute

2019-11-16 09:00 UTC, maciejkryger commented on src/main/java/pl/team/carrent/car_model/CarModelController.java
> +    }
zrobione na jednym, wywaliłem ten /add

2019-11-16 09:03 UTC, maciejkryger commented on src/main/java/pl/team/carrent/car_model/CarModelService.java
> +    }
zrobione

2019-11-16 09:07 UTC, maciejkryger commented on src/main/java/pl/team/carrent/car_model/CarModelController.java
> +    ModelAndView modelAndView = new ModelAndView("carModel");
ok, wywalone

2019-11-16 09:35 UTC, maciejkryger commented on src/main/java/pl/team/carrent/car_model/CarModelController.java
> +    public ModelAndView postCarModelEditModel(@RequestParam int id) {
poprawiłem

2019-11-16 09:35 UTC, maciejkryger commented on src/main/java/pl/team/carrent/car_model/CarModelController.java
> +    @PostMapping(value = "/")
ok,  przeniosłem wszystko do geta

2019-11-16 11:12 UTC, merged