mk-car-controller
JacobTheLiar/sda-4team-carrent pull request #45
Opened 2019-11-16 16:32 UTC by maciejkryger

changes in CarModel.jsp, CarModelController
added car controller and view

2019-11-16 20:03 UTC, JacobTheLiar requested changes
myślę że zmiany które zaproponowałem, są do zrobienia szybko

2019-11-16 20:03 UTC, JacobTheLiar commented on src/main/java/pl/team/carrent/car/CarController.java
> +        if (searchWhat == null || searchBy == null || searchWhat.isEmpty() || searchBy.isEmpty()) {
wydaje mi się, że można zbadać tylko `searchWat == null || searchWhat.isEmpty()`

2019-11-16 20:03 UTC, JacobTheLiar commented on src/main/java/pl/team/carrent/car_model/CarModelController.java
>          if (searchWhat == null || searchBy == null || searchWhat.isEmpty() || searchBy.isEmpty()) {
podobnie wydaje mi się, że można zbadać tylko `searchWhat == null || searchWhat.isEmpty()`

2019-11-16 20:03 UTC, JacobTheLiar commented on src/main/java/pl/team/carrent/car_model/CarModelController.java
>          modelAndViewToAddAndEdit.addObject("update", false);
zbędne jest przekazywanie flagi, czy edycja, dodaj nowy CarModel i użyj, będzie pusty.

2019-11-16 20:03 UTC, JacobTheLiar commented on src/main/java/pl/team/carrent/car_model/CarModelController.java
>          modelAndViewToAddAndEdit.addObject("update", true);
zbędne jest przekazywanie flagi, czy edycja, dodaj znaleziony CarModel i go wyświetl

2019-11-16 20:03 UTC, JacobTheLiar commented on src/main/webapp/WEB-INF/views/carDetail.jsp
> +    </c:if>
zbędne, jeżeli w kontrolerze przekażesz `new CarModel()`

2019-11-16 20:03 UTC, JacobTheLiar commented on src/main/webapp/WEB-INF/views/carDetail.jsp
> +    <c:if test="${update}">
zbędne, jeżeli w kontrolerze przekażesz `new CarModel()`

2019-11-16 20:03 UTC, JacobTheLiar commented on src/main/webapp/WEB-INF/views/carDetail.jsp
> +    </c:if>
zbędne, jeżeli w kontrolerze przekażesz `new CarModel()`

2019-11-16 20:03 UTC, JacobTheLiar commented on src/main/webapp/WEB-INF/views/carList.jsp
> +    <c:if test="${isFiltered}">
możesz tutaj zastosować składnię `${empty param.searchWhat}` i zrezygnować z przekazywania parametru `isFiltered`

2019-11-16 20:03 UTC, JacobTheLiar commented on src/main/webapp/WEB-INF/views/carList.jsp
> +        <input type="text" class="w3-bar-item w3-input w3-right" placeholder="szukaj..." name="searchWhat">
dodaj `value="${param.searchWhat}"` wtedy podczas kiedy szukasz będzie wypełnione pole

2019-11-16 20:03 UTC, JacobTheLiar commented on src/main/webapp/WEB-INF/views/carList.jsp
> +                <option value="${option.name()}">${option.description}</option>
jak poprawisz na `value="${option.name()}"${option.name()==param.searchBy ? ' selected' : ''}` wtedy zostanie zapamiętana pozycja którą przeszukujesz.

2019-11-16 20:03 UTC, JacobTheLiar commented on src/main/webapp/WEB-INF/views/carModelList.jsp
> +    <c:if test="${isFiltered}">
możesz tutaj zastosować składnię `${empty param.searchWhat}` i zrezygnować z przekazywania parametru `isFiltered`

2019-11-16 20:03 UTC, JacobTheLiar commented on src/main/webapp/WEB-INF/views/carModelList.jsp
> +        <input type="text" class="w3-bar-item w3-input w3-right" placeholder="szukaj..." name="searchWhat">
dodaj `value="${param.searchWhat}"` wtedy podczas kiedy szukasz będzie wypełnione pole

2019-11-16 20:03 UTC, JacobTheLiar commented on src/main/webapp/WEB-INF/views/carModelList.jsp
> +                <option value="${option.name()}">${option.description}</option>
jak poprawisz na `value="${option.name()}"${option.name()==param.searchBy ? ' selected' : ''}` wtedy zostanie zapamiętana pozycja którą przeszukujesz.

2019-11-16 20:05 UTC, JacobTheLiar commented
konflikt powstał, ponieważ grzebałem w `menu.html` przy zaczytaj z `developa` moje zmiany i zibacz ci sie stanie sie

2019-11-17 08:52 UTC, CKochanski commented on src/main/java/pl/team/carrent/car/CarController.java
> +        if (searchWhat == null || searchBy == null || searchWhat.isEmpty() || searchBy.isEmpty()) {
Nope, sprawdzić oba

2019-11-17 08:58 UTC, merged